-- Table: public.concretisation

-- DROP TABLE IF EXISTS public.concretisation;

CREATE TABLE IF NOT EXISTS public.concretisation
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    choice_question_answer_id integer NOT NULL,
    order_index integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    concretisation_value jsonb NOT NULL,
    CONSTRAINT concretisation_pkey PRIMARY KEY (id),
    CONSTRAINT concretisation_choice_question_answer_id_fkey FOREIGN KEY (choice_question_answer_id)
        REFERENCES public.choice_question_answer (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.concretisation
    OWNER to johr;

GRANT ALL ON TABLE public.concretisation TO johr;

GRANT ALL ON TABLE public.concretisation TO ug_massnahmen;