-- Table: public.survey

-- DROP TABLE IF EXISTS public.survey;

CREATE TABLE IF NOT EXISTS public.survey
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    survey_type_id integer NOT NULL,
    title character varying COLLATE pg_catalog."default" NOT NULL,
    created_by character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT survey_pkey PRIMARY KEY (id),
    CONSTRAINT survey_survey_type_id_fkey FOREIGN KEY (survey_type_id)
        REFERENCES public.survey_type (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.survey
    OWNER to johr;

GRANT ALL ON TABLE public.survey TO johr;

GRANT ALL ON TABLE public.survey TO ug_massnahmen;