-- Table: public.survey_type

-- DROP TABLE IF EXISTS public.survey_type;

CREATE TABLE IF NOT EXISTS public.survey_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    structure jsonb NOT NULL,
    CONSTRAINT "survey _structure_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.survey_type
    OWNER to johr;

GRANT ALL ON TABLE public.survey_type TO johr;

GRANT ALL ON TABLE public.survey_type TO ug_massnahmen;